# Generated by Django 5.0.7 on 2024-07-22 09:03

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_no', models.CharField(max_length=20, verbose_name='会員番号')),
                ('id_number', models.IntegerField(choices=[(1, '免許証'), (4, 'パスポート'), (5, 'その他(A4)')], verbose_name='証明の種類')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('furigana', models.CharField(max_length=100, verbose_name='フリガナ')),
                ('gender', models.IntegerField(choices=[(1, '男性'), (2, '女性')], verbose_name='性別')),
                ('birth_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='年')),
                ('birth_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='月')),
                ('birth_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='日')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='電話番号')),
                ('zip_code', models.CharField(max_length=7, verbose_name='郵便番号')),
                ('prefecture', models.CharField(max_length=4, verbose_name='都道府県')),
                ('city', models.CharField(max_length=100, verbose_name='市区町村')),
                ('address1', models.CharField(max_length=100, verbose_name='住所1')),
                ('address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='住所2')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日')),
            ],
            options={
                'verbose_name': '会員',
                'verbose_name_plural': '会員',
            },
        ),
    ]
